config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats do
  	resources :reviews
  end
  root 'cats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
	belongs_to :user
	belongs_to :cat_egory
	has_many :reviews

  has_attached_file :cat_image, :styles => { :cat_index => "250x350>", :cat_show  => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cat_image, :content_type => /\Aimage\/.*\z/
end

app/models/cat_egory.rb
class CatEgory < ApplicationRecord
	has_many :cats
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :cat
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :cats
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
	before_action :find_cat, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def index
		if params[:cat_egory].blank?
			@cats = Cat.all.order("created_at DESC")
		else
			@cat_egory_id = CatEgory.find_by(name: params[:cat_egory]).id
			@cats = Cat.where(:cat_egory_id => @cat_egory_id).order("created_at DESC")
		end
	end

	def new
		@cat = current_user.cats.build
		@cat_egories = CatEgory.all.map{ |c| [c.name, c.id]}
	end

	def show
		if @cat.reviews.blank?
			@average_review = 0
		else
			@average_review = @cat.reviews.average(:rating).round(2)
		end
	end

	def create
		@cat = current_user.cats.build(cat_params)
		@cat.cat_egory_id = params[:cat_egory_id]

		if @cat.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@cat_egories = CatEgory.all.map{ |c| [c.name, c.id]}
	end

	def update
		@cat_egories = CatEgory.all.map{ |c| [c.name, c.id]}
		if @cat.update(cat_params)
			redirect_to cat_path(@cat)
		else
			render 'edit'
		end
	end

	def destroy
		@cat.destroy
		redirect_to root_path
	end

	private

	def cat_params
		params.require(:cat).permit(:name, :personality, :owner, :cat_egory_id, :cat_image)
	end

	def find_cat
		@cat = Cat.find(params[:id])
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :find_cat
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)

		@review.cat_id = @cat.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to cat_path(@cat)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		@review = Review.find(params[:id])

		if @review.update(review_params)
			redirect_to cat_path(@cat)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to cat_path(@cat)
	end

	private

	def review_params
		params.require(:review).permit(:rating, :comment)
	end

	def find_cat
		@cat = Cat.find(params[:cat_id])
	end

	def find_review
		@review = Review.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cats/_form.html.erb
<%= simple_form_for @cat, :html => { :multipart => true } do |f| %>
	<%= select_tag(:cat_egory_id, options_for_select(@cat_egories), :prompt => "Select a Cat-Egory") %>
	<%= f.file_field :cat_image %>
	<%= f.input :name, label: "Cat Name" %>
	<%= f.input :personality %>
	<%= f.input :owner %>
	<%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/cats/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="edit-cat-form">
		<h1>Edit Cat</h1>

		<%= simple_form_for @cat, :html => { :multipart => true } do |f| %>
			<%= f.select :cat_egory_id, @cat_egories %>
			<%= f.file_field :cat_image %>
			<%= f.input :name, label: "Cat Name" %>
			<%= f.input :personality %>
			<%= f.input :owner %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>
	</div>
</div>

app/views/cats/index.html.erb
<h1 class="current-category"><%= params[:cat_egory]%></h1>

<% if @cats.count == 0 %>
	<h1> There are no cats in the cat-egory</h1>
<% else %>

	<div class="row">
		<% @cats.each do |cat| %>

			<div class="col-md-3">
				<a href="/cats/<%= cat.id %>">
					<%= image_tag cat.cat_image.url(:cat_index), class: "cat" %>
				</a>
			</div>

		<% end %>

	</div>

<% end %>

app/views/cats/new.html.erb
<div class="col-md-6 col-md-offset-3"> 
	<div class="new-cat-form">
		<h1> New cat</h1>

		<%= render 'form' %>
	</div>
</div>

app/views/cats/show.html.erb
<div class="row">
	<div class="col-md-4">
		<%= image_tag @cat.cat_image.url(:cat_show), class: "cat-show" %>
	</div>

	<div class="col-md-8">

		<div class="cat-info">

			<h2 class="cat-name"><span>Cat Name: </span><%= @cat.name %></h2>
			<h3 class="cat-owner"><span>Owner: </span><%= @cat.owner %></h3>
			<h2 class="avg-rating">Average Rating:</h2>
			<div class="average-review-rating" data-score=<%= @average_review %>></div>
			<span class="number-of-reviews"> Based On: <%= @cat.reviews.count %> reviews</span>
			<p class="cat-personality">About: <%= @cat.personality %></p>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-4">

		<div class="reviews">
			<h1> Reviews</h1>
			<%= render @cat.reviews %>

			<div>
				<%= link_to "Add Review", new_cat_review_path(@cat), class: "btn-custom"%>
			</div>
		</div>

	</div>

</div>

<div class="links btn-group">

	<%= link_to "Back", root_path, class: "btn btn-custom" %>
	<% if user_signed_in? %>
	
		<% if @cat.user_id == current_user.id %>
			<%= link_to "Edit", edit_cat_path(@cat), class: "btn btn-custom" %>
			<%= link_to "Delete", cat_path(@cat), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
		<% end %>
	<% end %>

</div>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets',
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateMyCat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<nav class="navbar navbar-default">
  		<div class="container">
  			<div class="navbar-header">
  				<%= link_to "Rate my cat", root_path, class: "navbar-brand"%>
  			</div>
  			<ul class="nav navbar-nav">
  				<li><%= link_to "Sign Up", new_user_registration_path%></li>

  				<% if user_signed_in? %>
  					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
  				<% else %>
  					<li><%= link_to "Log In", new_user_session_path %></li>
  				<%end %>

  			</ul>
  			<ul class="nav navbar-nav navbar-right">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              Cat-egories <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% CatEgory.all.each do |cat_egory| %>
                <li class="<%= 'active' if  params[:cat_egory] == cat_egory.name %>">
                  <%= link_to cat_egory.name, cats_path(cat_egory: cat_egory.name), class: "link" %>
                </li>
              <% end %>
            </ul>
          </li>
  				<% if user_signed_in? %>
  					<li><%= link_to "Add Cat", new_cat_path %></li>
  				<% end %>
  			</ul>
  		</div>
  	</nav>

  	<p class='notice'> <%= notice %> </p>
  	<p class="alert"><%= alert %></p>

    <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@cat, @cat.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets', scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">

	<div class = "review-rating" data-score="<%=review.rating %>"> </div>
	<p class="review-comment"><%= review.comment %></p>

	<% if user_signed_in? %>

		<% if review.user_id == current_user.id %>

			<div class="links btn-group">

				<%= link_to "Edit", edit_cat_review_path(review.cat, review), class: "btn btn-custom" %>
				<%= link_to "Delete", cat_review_path(review.cat, review), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-custom" %>
			</div>

		<% end %>
	<% end %>

</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">
		<h1>Edit Review </h1>

		<%= simple_form_for([@cat, @review]) do |f| %>
			<div id="rating-form">
				<label>Rating</label>
			</div>
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>
	</div>
</div>

<script>
	$('#rating-form').raty({
		path: '/assets', scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-review-form">
		<h1>New Review</h1>

		<%= render 'form' %>
	</div>
</div>